name: scaffold_tab_bar
description: A package to make it really easy to have optional nested navigation per tab.
version: 0.0.1
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/AppleEducate/plugins

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
